### PR TITLE
Bug fix for react native > 29

### PR DESCRIPTION
**Pull request by akki-ng**
App crash issues fixed and index.js added to ease up import like below

var FilePickerManager = require('react-native-file-picker');

onActivityResult was causing crash issues which have been fixed.

### CODE REVIEW

**Comment by akki-ng** [comment]
Thanks @luisfuertes

**Comment by luisfuertes** [comment]
Thanks you @akki-ng 

Im trying to implement your index, but it doesnt work.

I add Index.js with your code and in react-native-file-picker package add `"main": "index.js",`, but when i import, app crash with error: "Unknown name module: 'react-native-file-picker'" 

You know how can i fix it?

**Comment by akki-ng** [comment]
I will take a look, but its done in my fork and its working. Will you please make sure that the index.js file setup is done correctly?

**Comment by luisfuertes** [comment]
I think all its ok. Can you verify [on my repo code](https://github.com/luisfuertes/react-native-file-picker)?

Do you want that i implement your size and name file parameters on my repo?

**Pull request closed without merging**
